import { PageSchema } from "@/components/constructor/page-render/types";

const refundPolicySchema: PageSchema = {
    meta: {
        title: "Refund & Return Policy – Cheffmate",
        description:
            "Official Refund & Return Policy for Cheffmate: refunds for tokens, chef courses, AI cooking plans, and consumer rights.",
        keywords: [
            "refund policy",
            "return policy",
            "cheffmate",
            "tokens",
            "AI cooking",
            "digital content",
            "consumer rights",
        ],
        canonical: "/refund-policy",
        ogImage: {
            title: "Cheffmate – Refund & Return Policy",
            description: "Transparent refund and return policy for Cheffmate cooking platform.",
            bg: "#ffffff",
            color: "#000000",
        },
    },
    blocks: [
        {
            type: "text",
            title: "Refund & Return Policy",
            description: "Effective date: 20 February 2026",
        },
        {
            type: "text",
            title: "1. Summary",
            bullets: [
                "Request Handling: All refund requests are processed under this Policy and applicable UK consumer law, specifically taking into account the digital and educational nature of our services.",
                "Processing Time: Typically 5–10 business days after approval (banking timelines may vary).",
                "Token Usage: Tokens function as a non-refundable digital credit. Once Tokens are consumed to unlock a Chef Course or generate an AI Cooking Plan, they cannot be refunded.",
                "Digital Nature: The Service provides digital video content, text, and intellectual property. There are no physical items (such as ingredients or cooking equipment) to ship or return.",
                "Result Disclaimer: We do not offer refunds based on the outcome of your cooking endeavors (e.g., you did not like the taste of the dish, or your meal burned) or personal preference regarding the chef's teaching style.",
                "Contact: To submit a request, email contact@cheffmate.co.uk with your Account details.",
            ],
        },
        {
            type: "text",
            title: "2. Scope and Legal Notice",
            description:
                "This Refund & Return Policy (“Policy”) governs all cancellations, disputes, and refund requests for purchases made via cheffmate.co.uk, including Token purchases and the redemption of Tokens for Chef Courses or AI Cooking Plans.\n\nThe Service is operated by FUSION FAIRIES LTD (Company Number 15613978), registered at 20 Wenlock Road, London, England, N1 7GU (“Cheffmate”, “we”, “us”, “our”).\n\nNothing in this Policy is intended to limit your statutory rights under UK law (including the Consumer Rights Act 2015 and Consumer Contracts Regulations 2013), except where distinct exemptions for digital content apply.",
        },
        {
            type: "text",
            title: "3. Key Definitions",
            bullets: [
                "Tokens: The digital credit balance in your Account used to unlock content.",
                "Deliverables / Digital Content: Any Chef Courses (videos, recipes, theory) or AI Cooking Plans generated by our system based on your input.",
                "Service Types: Chef Courses: Pre-recorded, structured culinary content provided by professionals. AI Cooking Assistant: Automated, personalized cooking plans delivered digitally.",
                "Order: A confirmed purchase of Token packages.",
            ],
        },
        {
            type: "text",
            title: "4. General Refund Principles",
            description:
                "4.1. The \"No Return\" Nature of Digital Data. By purchasing Tokens and clicking \"Unlock Course\" or \"Start with AI\", you expressly consent to the immediate performance of the contract. You acknowledge that once the digital content is made available to your Dashboard, you lose your statutory right of withdrawal (the 14-day cooling-off period) for those specific Tokens.\n\n4.2. Refund Cap. Any refund granted is strictly limited to the fiat amount paid for the specific Token transaction. We are not liable for any third-party fees, bank overdraft fees, or currency exchange losses.\n\n4.3. Accuracy of Client Input (AI Plans). Our AI Deliverables are created based on the data you provide (dietary needs, skill level, available ingredients). If your input is incomplete, unrealistic, or incorrect, the resulting cooking plan may be suboptimal. Re-generating the plan with new data requires new Tokens and is not grounds for a free revision or refund.\n\n4.4. Subjectivity & Cooking Results. Cheffmate provides educational tools and recipes, not a private catering service. A refund will not be issued if: You do not like the taste, texture, or appearance of the final dish; You disagree with a professional chef's technique or teaching style; You do not like the formatting or vocabulary of the AI-generated text; You decide to abandon the course or recipe after unlocking it.",
        },
        {
            type: "text",
            title: "5. Token Purchases (Wallet Top-ups)",
            description:
                "5.1. Prepayment Only. Tokens are sold as bundles (e.g., Starter, Cook Pro, Chef Mode). Unused Tokens are generally non-refundable outside the 14-day statutory cancellation window and cannot be exchanged for cash.\n\n5.2. Exceptional Refunds (14-Day Rule). If you have purchased a Token package and have not used a single Token from that specific package, you may request a full refund to your original payment method within 14 days of purchase. Once a Token is used (even partially), the entire bundle is considered \"opened\" and non-refundable. We do not issue partial refunds for partially used Token packages.\n\n5.3. Expiry & Inactivity. While Tokens do not expire under normal usage, we reserve the right to clear Token balances on dormant accounts that have seen zero activity (no logins or Token usage) for a continuous period of 24 months.",
        },
        {
            type: "text",
            title: "6. Cancellations of Specific Services",
            description:
                "6.1. Chef Courses & AI Cooking Plans. These services are fulfilled digitally. Once you confirm the usage of Tokens, they are consumed immediately to unlock the course or trigger the AI generation. No cancellation or refund of Tokens is possible after this action.",
        },
        {
            type: "text",
            title: "7. Quality Issues & Technical Faults",
            description:
                "7.1. Technical Defects. If a Deliverable is technically defective (e.g., a video course fails to load, the file is completely corrupted, or the AI returns a blank page due to a system error), you must notify us within 7 days. We will: Restore your access to the content; or Credit your Account with the exact amount of Tokens lost due to the error; Refunds to the bank card are only issued if we are unable to rectify the technical fault and you prefer not to receive Tokens.\n\n7.2. \"As Is\" AI Content. AI-generated content is provided \"as is\". Minor factual hallucinations, bizarre ingredient combinations, or generic phrasing inherent to Large Language Models (LLMs) are not considered technical \"defects\" eligible for a refund. You are expected to use common sense when reviewing AI recipes.",
        },
        {
            type: "text",
            title: "8. How to Request a Refund",
            description:
                "To raise a claim, please email contact@cheffmate.co.uk with the subject line \"Refund Request\". You must include:",
            bullets: [
                "Account Email Address.",
                "Description of the issue (e.g., \"Video not loading\", \"Duplicate token charge\").",
                "Evidence (Screenshots of the error, bank statement for a double charge).",
                "Timeline: We aim to acknowledge receipt within 48 hours.",
                "We will investigate and provide a decision within 5 business days.",
                "Approved fiat refunds are processed within 5–10 business days (funds may take longer to appear depending on your bank).",
            ],
        },
        {
            type: "text",
            title: "9. Chargebacks & Disputes",
            description:
                "9.1. Friendly Fraud. If you initiate a chargeback with your bank for a validly delivered Token package or digital service (e.g., claiming \"Service not received\" after actively watching a Chef Course), we classify this as \"Friendly Fraud\".\n\n9.2. Consequences. In the event of an unjustified chargeback: Your Account will be permanently suspended; We will dispute the chargeback by providing full logs to your bank, including your IP address, Token redemption history, and content access logs.\n\n9.3. Resolution. We strongly encourage you to contact our support team before contacting your bank. We are often able to resolve issues (e.g., reimbursing lost Tokens due to a glitch) faster than the banking dispute process.",
        },
        {
            type: "text",
            title: "10. Taxes",
            description:
                "Prices are exclusive of applicable taxes unless stated otherwise at checkout. If a fiat refund is issued, we will refund the tax amount only if we are able to reclaim it from the tax authorities or if required by law.",
        },
        {
            type: "text",
            title: "11. Data Protection",
            description:
                "To process refunds and handle disputes, we may retain transaction data (including Order references and activity logs) for up to 6 years in compliance with UK tax and accounting laws. This processing is conducted in accordance with our Privacy Policy.",
        },
        {
            type: "text",
            title: "12. Illustrative Examples",
            bullets: [
                "Scenario A (No Refund): You bought the Cook Pro package (25,000 Tokens), spent 5,000 Tokens on a French Cuisine course, watched one video, and decided it was too difficult. Result: Tokens are consumed. The 14-day cooling-off right is lost for the entire package because you started using it. No refund.",
                "Scenario B (Refund Approved): You tried to buy 5,000 Tokens (£5.00) but the website froze, and your card was charged twice. Result: We will refund the duplicate £5.00 transaction in full to your card.",
                "Scenario C (Token Reimbursement): You spent Tokens on the AI Cooking Assistant, but the system crashed and delivered an empty page. Result: Contact support. We will refund the exact amount of spent Tokens back to your Cheffmate balance so you can try again.",
            ],
        },
        {
            type: "text",
            title: "13. Contact Details",
            bullets: [
                "FUSION FAIRIES LTD",
                "Company Number: 15613978",
                "Registered Office: 20 Wenlock Road, London, England, N1 7GU",
                "Phone: +44 7537 127672",
                "Email: contact@cheffmate.co.uk",
            ],
        },
    ],
};

export default refundPolicySchema;
