import { PageSchema } from "@/components/constructor/page-render/types";

const termsSchema: PageSchema = {
    meta: {
        title: "Terms and Conditions – Cheffmate",
        description:
            "Official Terms and Conditions for using Cheffmate.co.uk – rules, payments, tokens, refunds, liability, and user rights.",
        keywords: [
            "terms and conditions",
            "cheffmate",
            "tokens",
            "refunds",
            "chef course",
            "AI cooking",
            "digital content",
        ],
        canonical: "/terms-and-conditions",
        ogImage: {
            title: "Cheffmate – Terms and Conditions",
            description: "Full Terms and Conditions for Cheffmate cooking platform.",
            bg: "#ffffff",
            color: "#000000",
        },
    },
    blocks: [
        {
            type: "text",
            title: "Terms and Conditions",
            description: "Effective date: 20 January 2026",
        },
        {
            type: "text",
            title: "1. Introduction",
            description:
                "1.1. These Terms and Conditions (“Terms”) govern your access to and use of the Cheffmate.co.uk website and services (the “Service”), operated by FUSION FAIRIES LTD (company number: 15613978, registered office: 20 Wenlock Road, London, England, N1 7GU) (“we”, “us”, “our”).\n\n1.2. By accessing or using the Service, creating an Account, or purchasing Tokens, Chef Courses, or AI Cooking Plans, you agree to be bound by these Terms. If you do not agree, you must not use the Service.",
        },
        {
            type: "text",
            title: "2. Definitions",
            bullets: [
                '"Account" means the user profile created on the Service.',
                '"Chef Course" means pre-recorded or structured culinary courses and digital learning materials created by professional chefs.',
                '"AI Cooking Plan" means a personalised culinary plan or recipe generated by our AI Cooking Assistant.',
                '"Digital Content" refers collectively to Chef Courses and AI Cooking Plans.',
                '"Token(s)" means the internal virtual unit of account used exclusively to unlock Digital Content within the platform.',
            ],
        },
        {
            type: "text",
            title: "3. Eligibility and Account Registration",
            description:
                "3.1. You must be at least 18 years old to register.\n\n3.2. You must provide accurate information. You are responsible for safeguarding your login details.\n\n3.3. You must notify us immediately at contact@cheffmate.co.uk of any unauthorised use.",
        },
        {
            type: "text",
            title: "4. Tokens, Pricing, and Payments",
            description:
                "4.1. Nature of Tokens: Tokens are an internal credit system to access Digital Content. They are not legal tender or financial instruments and cannot be exchanged for cash outside the platform.\n\n4.2. Pricing and Taxes: Prices displayed for Token packages are exclusive of applicable taxes (such as VAT). Any applicable taxes will be calculated and added to your total at checkout before payment confirmation.\n\n4.3. Payments: We use secure, third-party payment processors to handle transactions. By submitting payment details, you authorise us (via our processors) to charge the total amount.\n\n4.4. Dormant Accounts: If your Account remains completely inactive for a continuous period of 24 months, we reserve the right to classify the Account as \"dormant\" and clear the Token balance, upon sending a 30-day prior written notice.",
        },
        {
            type: "text",
            title: "5. Scope of Services & Delivery",
            description:
                "5.1. Scope of Services: Depending on your choices, the Services purchased via Tokens may include:\n\n• Chef Courses: Structured culinary courses provided by real professional chefs.\n• AI Cooking Assistant: Automated generation of personalised cooking plans based on your optional inputs (e.g., diet, skill level).\n\n5.2. Delivery Policy:\n\n• Digital Delivery: All Digital Content is provided digitally. It will be available directly in your Account dashboard and/or a notification will be sent to your registered email address.\n• Timeframes: Chef Courses: Delivered and accessible in your dashboard immediately upon Token redemption. AI Cooking Plans: Generated and delivered to your dashboard typically within 4 hours of submitting your request.\n• Deemed Acceptance: You have a period of 7 days from delivery to review the Digital Content. If no technical issues or severe defects are reported to support within this timeframe, the Service is deemed successfully completed.\n\n5.3. Technical Compatibility: We do not guarantee that all third-party software, older browsers, or outdated devices will render the video courses or text documents perfectly.",
        },
        {
            type: "text",
            title: "6. Refunds, Cancellation and Consumer Rights",
            description:
                "6.1. Right to Cancel: Under consumer law, you have 14 days to cancel your purchase of a Token package, provided you have not used any of the Tokens.\n\n6.2. Loss of Right: By redeeming Tokens to unlock a course or generate an AI plan, you consent to immediate digital delivery and lose your right to a refund for those spent Tokens.\n\n6.3. Requesting a Refund: All refund requests for unused Tokens or reports of severely defective Digital Content (e.g., AI hallucinations or technical errors) must be sent to our support team at contact@cheffmate.co.uk. We do not process automatic refunds.",
        },
        {
            type: "text",
            title: "7. Independent Contractors & Platform Role",
            description:
                "7.1. FUSION FAIRIES LTD acts as a platform facilitating culinary education. The professional chefs providing Chef Courses on our platform are independent contractors/freelancers, not our employees.\n\n7.2. While we carefully select our chef partners, the opinions, techniques, and advice expressed in Chef Courses belong solely to the respective chefs.",
        },
        {
            type: "text",
            title: "8. Health, Safety, and AI Disclaimers",
            description:
                "8.1. Health & Safety: Cooking involves inherent risks (knives, heat, raw food). You assume full responsibility for your safety. We are not liable for injuries, food poisoning, or property damage.\n\n8.2. AI-Generated Content: Our AI Cooking Assistant utilizes advanced machine learning models. While we strive for accuracy, AI can produce unexpected or inaccurate results. You are solely responsible for reviewing AI recipes for correct cooking times, safe temperatures, and common sense.\n\n8.3. Allergies: Providing dietary or allergy information to the AI is optional. If provided, the AI will attempt to accommodate it, but you must strictly verify all ingredients yourself. Cheffmate provides education, not medical advice.",
        },
        {
            type: "text",
            title: "9. Intellectual Property",
            description:
                "9.1. All intellectual property in the platform and Digital Content belongs to us or our licensors/chef partners.\n\n9.2. You are granted a non-exclusive, non-transferable licence for personal use only. Reselling or distributing the content is strictly prohibited.",
        },
        {
            type: "text",
            title: "10. Limitation of Liability & Indemnity",
            description:
                "10.1. Nothing excludes liability for death or personal injury caused by our direct negligence or fraud.\n\n10.2. Our total liability to you shall not exceed the amount paid by you for Tokens in the 12 months preceding the claim. We are not liable for indirect or consequential losses.\n\n10.3. You agree to indemnify FUSION FAIRIES LTD and its independent contractors against claims resulting from your misuse of the Service or gross negligence in the kitchen.",
        },
        {
            type: "text",
            title: "11. Data Protection",
            description:
                "We process personal data, including optional dietary inputs, in accordance with our Privacy Policy.",
        },
        {
            type: "text",
            title: "12. Changes, Law, and Jurisdiction",
            description:
                "12.1. We may update these Terms from time to time. Continued use constitutes acceptance.\n\n12.2. These Terms are governed by the laws of England and Wales. Courts of England and Wales shall have exclusive jurisdiction (subject to mandatory local consumer rights).",
        },
        {
            type: "text",
            title: "13. Contact Details",
            bullets: [
                "FUSION FAIRIES LTD",
                "Company number: 15613978",
                "Registered office: 20 Wenlock Road, London, England, N1 7GU",
                "Phone: +44 7537 127672",
                "Email: contact@cheffmate.co.uk",
            ],
        },
    ],
};

export default termsSchema;
