import { PageSchema } from "@/components/constructor/page-render/types";

const COMPANY_LEGAL_NAME = "FUSION FAIRIES LTD";
const COMPANY_NUMBER = "15613978";
const COMPANY_ADDRESS = "20 Wenlock Road, London, England, N1 7GU";
const COMPANY_EMAIL = "contact@cheffmate.co.uk";
const COMPANY_PHONE = "+44 7537 127672";

const termsSchema: PageSchema = {
    meta: {
        title: "Terms and Conditions – Cheffmate",
        description:
            "Official Terms and Conditions for using Cheffmate.co.uk – access, tokens, payments, refunds, liability, and user rights.",
        keywords: [
            "terms and conditions",
            "cheffmate",
            "tokens",
            "refunds",
            "AI cooking plan",
            "chef course",
            "digital culinary services",
        ],
        canonical: "/terms-and-conditions",
        ogImage: {
            title: "Cheffmate – Terms and Conditions",
            description: "Full Terms and Conditions for Cheffmate platform.",
            bg: "#ffffff",
            color: "#000000",
        },
    },
    blocks: [
        {
            type: "text",
            title: "Terms and Conditions",
            description:
                `Effective date: 7 April 2026 \n\nThese Terms and Conditions (“Terms”) govern your access to and use of the Cheffmate website, platform, account area, dashboard, forms, and related digital culinary services available at https://www.cheffmate.co.uk (the “Service”).\n\nThe Service is operated by:\n${COMPANY_LEGAL_NAME}\nCompany Number: ${COMPANY_NUMBER}\nAddress: ${COMPANY_ADDRESS}\nEmail: ${COMPANY_EMAIL}\nPhone: ${COMPANY_PHONE}\n\nThroughout these Terms, “Company”, “we”, “us”, and “our” refer to ${COMPANY_LEGAL_NAME}. “You” and “your” refer to the person or entity using the Service.\n\nBy accessing or using the Service, creating an account, purchasing Tokens, redeeming Tokens, requesting AI-generated content, or accessing chef-created content through the Service, you agree to be bound by these Terms. If you do not agree, you must not use the Service.`,
        },
        {
            type: "text",
            title: "1. Definitions",
            description: "For the purposes of these Terms:",
            bullets: [
                "Account means your registered user account on the Service.",
                "Tokens means the internal prepaid digital credits used within the Service to access or redeem paid features, chef-created content, AI-generated content, and related digital services. Tokens are an internal accounting mechanism only.",
                "Chef Course means culinary learning materials, courses, plans, recipes, guides, modules, lessons, PDFs, or other digital culinary content created, curated, prepared, or contributed by a human chef or culinary specialist made available through the Service.",
                "AI Cooking Plan means culinary guidance, recipes, plans, suggestions, or related digital output generated or assisted by automated systems or artificial intelligence made available through the Service.",
                "Digital Content means all digitally delivered content available through the Service, including Chef Courses, AI Cooking Plans, guides, plans, lesson materials, recipe files, and downloadable materials.",
                "Order means a completed purchase of Tokens and/or a completed redemption of Tokens for Digital Content or another paid Service.",
                "Services means all products, features, content, tools, functionality, and digital services made available through the Service.",
            ],
        },
        {
            type: "text",
            title: "2. Eligibility and Account Registration",
            bullets: [
                "2.1 You must be at least 18 years old to use the Service and create an Account.",
                "2.2 If you use the Service on behalf of a company or other legal entity, you represent and warrant that you have authority to bind that entity to these Terms.",
                "2.3 You must provide accurate, current, and complete information when registering an Account, placing an Order, submitting prompts, questionnaires, dietary preferences, or other information through the Service.",
                "2.4 You are responsible for maintaining the confidentiality of your login credentials and for all activity carried out through your Account.",
                `2.5 You must promptly notify us at ${COMPANY_EMAIL} if you suspect unauthorised access to your Account or any other security breach.`,
                "2.6 We may refuse registration, suspend an Account, request verification, or restrict access where reasonably necessary for security, fraud prevention, legal compliance, abuse prevention, or operational reasons.",
            ],
        },
        {
            type: "text",
            title: "3. Nature of the Service",
            bullets: [
                "3.1 Cheffmate is a digital culinary education and cooking-content platform through which users may purchase Tokens and redeem them for Digital Content and related digital services.",
                "3.2 The Service is provided online only. Unless expressly stated otherwise, we do not sell or deliver physical goods.",
                "3.3 The Service may include both human-created content and AI-assisted or AI-generated content. The format, features, timing, and delivery method may vary depending on the selected offering.",
                "3.4 We may change, update, improve, limit, suspend, remove, or discontinue any part of the Service at any time for legal, technical, security, operational, or commercial reasons.",
                "3.5 We do not guarantee that every chef, course, AI feature, content category, language option, or pricing structure will remain available at all times.",
            ],
        },
        {
            type: "text",
            title: "4. Tokens",
            bullets: [
                "4.1 Tokens are prepaid internal digital credits used solely within the Service.",
                "4.2 Tokens are not legal tender, electronic money, payment instruments, bank deposits, investments, securities, or cryptoassets.",
                "4.3 Tokens:",
                "(a) do not accrue interest;",
                "(b) have no cash value outside the Service;",
                "(c) cannot be withdrawn as cash;",
                "(d) are not transferable unless we expressly agree otherwise in writing; and",
                "(e) cannot be resold, assigned, pledged, or exchanged outside the Service.",
                "4.4 Purchased Tokens are credited to your Account after successful payment authorisation and processing.",
                "4.5 Tokens are deducted when you redeem them for Digital Content or another paid Service, or when performance of the relevant digital service begins.",
                "4.6 Unless expressly stated otherwise on the Service, purchased Tokens do not expire while your Account remains open and in good standing. This does not limit our right to adjust or remove Token balances affected by payment reversal, chargeback, fraud, abuse, manifest error, unauthorised activity, or legal obligation.",
                "4.7 We may offer promotional, trial, bonus, or goodwill Tokens. Unless expressly stated otherwise, such Tokens are non-refundable, non-transferable, and may be subject to separate conditions, limitations, or expiry periods.",
                "4.8 We reserve the right to correct Token balances affected by manifest error, technical malfunction, duplicate crediting, fraud, abuse, payment reversal, or unauthorised activity.",
            ],
        },
        {
            type: "text",
            title: "5. Payment Options, Pricing, and Billing Terms",
            bullets: [
                "5.1 We currently accept payment by Visa and Mastercard, subject to availability of our payment providers and any fraud-prevention or verification checks.",
                "5.2 We currently support purchases in GBP, EUR, USD, and NOK, as displayed on the Service or at checkout.",
                "5.3 Token packages made available on the Service may include, as applicable at the time of purchase:",
                "• Kitchen Warm-Up — 500 Tokens — £5.00 / €5.85 / $6.45 / kr64.25",
                "• AI Chef Boost — 1,500 Tokens — £15.00 / €17.55 / $19.35 / kr192.75",
                "• Master Chef Week — 5,000 Tokens — £50.00 / €58.50 / $64.50 / kr642.50",
                "• Flexible Token Pack — a custom Token amount and corresponding price shown at checkout",
                "5.4 We may change pricing, package names, package availability, supported currencies, exchange logic, or checkout presentation from time to time. Changes apply prospectively and do not affect an Order already accepted, except where there is an obvious pricing or technical error.",
                "5.5 The price payable for your Order is the price shown to you at checkout in the selected currency before you confirm payment. Any taxes, if applicable, will be shown as required before you complete the transaction.",
                "5.6 Your bank, card issuer, or payment provider may apply foreign transaction fees, currency conversion spreads, or other charges outside our control. We are not responsible for such third-party charges.",
                "5.7 By submitting payment details, you represent and warrant that:",
                "(a) you are authorised to use the selected payment method;",
                "(b) the payment information provided is accurate and complete; and",
                "(c) there are sufficient funds or credit available to complete the transaction.",
                "5.8 All payments are subject to authorisation, fraud screening, and verification by us and/or our third-party payment processors. We may decline, hold, or cancel an Order where reasonably necessary for fraud prevention, payment security, legal compliance, or abuse prevention.",
                "5.9 If a payment is declined, reversed, charged back, disputed without valid basis, or later found to be unauthorised, we may:",
                "(a) refuse or reverse the relevant Token credit;",
                "(b) suspend or restrict your Account;",
                "(c) revoke access to related Digital Content to the extent permitted by law;",
                "(d) withhold pending delivery; and/or",
                "(e) take reasonable recovery steps.",
                "5.10 You must contact us promptly if you believe you have been charged incorrectly. We may require reasonable evidence to investigate and resolve the issue.",
            ],
        },
        {
            type: "text",
            title: "6. Orders, Delivery, Cancellations, and Refund Terms",
            bullets: [
                "6.1 General Order Terms",
                "6.1.1 All Orders are subject to our acceptance.",
                "6.1.2 An Order for Tokens is placed when you complete checkout and your payment is successfully authorised and processed.",
                "6.1.3 An Order for Digital Content is placed when:",
                "(a) you have sufficient Tokens in your Account or otherwise complete the required payment step;",
                "(b) you submit any information reasonably required for the selected content or feature; and",
                "(c) you confirm the relevant redemption or request through the Service.",
                "6.1.4 We may refuse, cancel, reverse, or place an Order on hold where reasonably necessary, including in cases of suspected fraud, payment issues, inaccurate information, technical errors, abuse, legal compliance requirements, or inability to fulfil the Order.",
                "6.2 Delivery of Tokens",
                "6.2.1 Purchased Tokens are normally credited electronically to your Account shortly after successful payment confirmation.",
                "6.2.2 If Token crediting is delayed due to a technical issue attributable to us, we will use reasonable efforts to correct the issue within a reasonable period.",
                "6.3 Delivery of Digital Content",
                "6.3.1 All Chef Courses, AI Cooking Plans, and other Digital Content are delivered digitally only.",
                "6.3.2 Delivery is normally made by making the relevant content available in your Account, dashboard, download area, or another digital delivery method designated on the Service.",
                "6.3.3 AI Cooking Plans are ordinarily generated and delivered after we receive the information reasonably required to process your request. Where the Service states an estimated timeframe, such as delivery within up to 4 hours, that timeframe is an estimate unless we expressly state otherwise.",
                "6.3.4 Chef Courses or chef-created content may be delivered immediately, progressively, or after preparation, depending on the specific offering selected and the workflow shown on the Service.",
                "6.3.5 Delivery times may vary depending on content type, the completeness and accuracy of information submitted by you, chef availability, moderation, technical factors, internal review, queue volume, and other operational circumstances.",
                "6.3.6 Digital Content is deemed delivered when it has been made available to you electronically through the designated delivery method.",
                "6.3.7 You are responsible for ensuring that the information you submit is accurate, complete, and suitable for processing. We are not responsible for delays, unsuitable outputs, or fulfilment problems caused by incomplete, inconsistent, inaccurate, or misleading information submitted by you.",
                "6.4 Consumer Cancellation Rights for Token Purchases",
                "6.4.1 Nothing in these Terms limits any mandatory consumer rights that apply to you under applicable law.",
                "6.4.2 If you are a consumer and purchase Tokens, you may have a statutory right to cancel that purchase within 14 days from the date of purchase, provided that the Tokens have not been used, redeemed, spent, consumed, or mixed with promotional or bonus credits in a way that makes separation impracticable.",
                "6.4.3 Where cancellation is validly exercised for unused purchased Tokens, we will refund the relevant amount to the original payment method within the period required by applicable law.",
                "6.4.4 Promotional, bonus, trial, or goodwill Tokens are not cash purchases and are not refundable unless required by law.",
                "6.5 Immediate Supply of Digital Content and Loss of Cancellation Right",
                "6.5.1 By redeeming Tokens for Digital Content, requesting immediate access, requesting AI generation, or requesting commencement of a custom or chef-created order, you expressly request immediate performance of a digital service and/or immediate supply of digital content.",
                "6.5.2 To the extent permitted by applicable law, you acknowledge that once supply has begun, generation has started, access has been granted, or substantial work on a customised order has commenced, your statutory withdrawal or cancellation right may be lost.",
                "6.5.3 For AI Cooking Plans, performance is treated as having begun once processing of your request starts.",
                "6.5.4 For chef-created or customised content, performance may be treated as having begun once the request has been accepted for preparation, assigned, queued for production, or otherwise entered into active fulfilment.",
                "6.6 Refund Rules",
                "6.6.1 Used or redeemed Tokens are non-refundable except:",
                "(a) where required by applicable law;",
                "(b) where we fail to provide the purchased Service;",
                "(c) where the relevant Digital Content is materially defective and we cannot correct or re-deliver it within a reasonable period; or",
                "(d) where we expressly agree otherwise.",
                "6.6.2 Refunds are not available merely because:",
                "(a) you changed your mind after delivery or performance began;",
                "(b) you no longer wish to use the Service;",
                "(c) you subjectively dislike the culinary style, presentation, recipe choice, or format of content that was substantially delivered as described;",
                "(d) you entered incomplete, incorrect, contradictory, or unsuitable prompts or preferences; or",
                "(e) you failed to review ingredient suitability, allergies, dietary restrictions, equipment requirements, timing, or food-safety steps before acting on the content.",
                `6.6.3 If you believe Tokens were deducted incorrectly, content was not delivered, or a delivered output is materially defective, you must contact us at ${COMPANY_EMAIL} and provide sufficient details for review.`,
                "6.6.4 Where a technical or fulfilment issue is attributable to us, we may, at our discretion and where appropriate, re-deliver the content, correct the issue, restore the relevant Tokens, or provide a refund.",
                "6.6.5 Refunds, where approved, will ordinarily be made to the original payment method unless otherwise required by law or agreed for operational reasons.",
                "6.7 Cancellation by Us",
                "6.7.1 We may cancel or decline an Order before fulfilment begins where reasonably necessary for fraud prevention, payment integrity, legal compliance, abuse prevention, technical failure, or inability to fulfil.",
                "6.7.2 If we cancel a paid Order before the purchased Tokens are credited or before redeemed content delivery begins, we will ordinarily restore the relevant Tokens or refund the affected payment, as appropriate.",
            ],
        },
        {
            type: "text",
            title: "7. Independent Contractors and Platform Role",
            bullets: [
                `7.1 Cheffmate is operated by ${COMPANY_LEGAL_NAME} as the platform operator. We provide the website, account infrastructure, Token system, checkout flow, digital delivery environment, and related support and administrative functions.`,
                "7.2 Some content made available through the Service is created, contributed, or prepared by chefs, culinary specialists, or other contributors who act as independent contractors or freelancers unless we expressly state otherwise.",
                "7.3 Independent contractors engaged in connection with the Service are not, solely by reason of their participation on the platform:",
                "(a) our employees;",
                "(b) your employees;",
                "(c) your agents;",
                "(d) our general agents with authority to bind us; or",
                "(e) parties to a partnership or joint venture with you.",
                `7.4 Unless expressly stated otherwise on a specific product page or in a separate written agreement, your contract for use of the Service, purchase of Tokens, and access to Digital Content is with ${COMPANY_LEGAL_NAME}, not directly with an individual chef.`,
                "7.5 We may curate, review, moderate, organise, publish, remove, or suspend chef-created content on the platform, but the culinary style, opinions, methods, educational approach, and creative expression reflected in chef-created content may remain those of the relevant chef or contributor.",
                "7.6 We do not guarantee the ongoing availability of any specific chef, contributor, content creator, course, cuisine category, or teaching style.",
                "7.7 Independent contractors are responsible for their own professional conduct, taxes, insurance, and regulatory obligations applicable to them in their own capacity. Nothing in these Terms creates an employment relationship between us and any user, or between any user and any chef.",
                "7.8 Unless the Service expressly offers a direct communication feature or a specific one-to-one service, purchase of Tokens or content through the platform does not entitle you to direct personal access, private consultation, or ongoing support from any individual chef.",
                "7.9 We are not a culinary school, licensing authority, professional certification body, or medical or nutritional advisory provider. Any educational or culinary content made available through the Service is offered for informational and learning purposes only.",
                `7.10 Complaints about payments, Token balances, account access, delivery issues, or platform functionality must be directed to us at ${COMPANY_EMAIL}.`,
            ],
        },
        {
            type: "text",
            title: "8. Kitchen Safety, Dietary Information, and AI Disclaimer",
            bullets: [
                "8.1 The Service and all Digital Content are provided for general culinary education, inspiration, and informational purposes only.",
                "8.2 The Service does not provide medical advice, diagnosis, treatment, allergy testing, emergency advice, or professional nutritional counselling.",
                "8.3 Cooking involves inherent risks, including risks associated with sharp tools, heat, raw ingredients, food contamination, allergic reactions, and improper storage or handling.",
                "8.4 You are solely responsible for:",
                "(a) checking ingredients and allergens;",
                "(b) verifying cooking times and safe temperatures;",
                "(c) ensuring recipes are suitable for your dietary, allergy, medical, religious, or household needs;",
                "(d) using proper kitchen safety practices; and",
                "(e) exercising appropriate judgment before preparing, serving, or consuming any dish.",
                "8.5 If you provide information about allergies, intolerances, dietary preferences, or health-related restrictions, you remain responsible for independently verifying the suitability and safety of any output.",
                "8.6 AI-generated outputs may contain errors, omissions, unsuitable substitutions, inaccurate assumptions, or unexpected results. You must review them carefully before relying on them.",
                "8.7 To the fullest extent permitted by law, we are not responsible for injury, illness, allergic reaction, food spoilage, property damage, or other loss arising from your preparation, serving, or consumption of dishes based on content obtained through the Service, except where liability cannot lawfully be excluded.",
            ],
        },
        {
            type: "text",
            title: "9. User Inputs and Acceptable Use",
            bullets: [
                "9.1 You are solely responsible for all information, prompts, requests, submissions, dietary details, files, and materials you submit through the Service.",
                "9.2 You represent and warrant that your submissions:",
                "(a) are accurate and not misleading to the best of your knowledge;",
                "(b) are lawful;",
                "(c) do not infringe third-party rights; and",
                "(d) do not contain malicious or harmful code.",
                "9.3 You must not use the Service:",
                "(a) unlawfully or fraudulently;",
                "(b) to submit false or misleading information;",
                "(c) to interfere with the operation, security, or integrity of the Service;",
                "(d) to gain unauthorised access to accounts, systems, or data;",
                "(e) to scrape, extract, reverse engineer, or commercially exploit the Service or its outputs without authorisation;",
                "(f) to abuse promotional offers or Token mechanisms; or",
                "(g) in a way that could damage our reputation, infrastructure, or legal position.",
            ],
        },
        {
            type: "text",
            title: "10. Intellectual Property Rights",
            bullets: [
                "10.1 All intellectual property rights in the Service, including its software, design, branding, text, graphics, databases, structure, and underlying systems, are owned by us or licensed to us.",
                "10.2 Subject to your compliance with these Terms and completion of the relevant payment or redemption, we grant you a limited, revocable, non-exclusive, non-transferable, non-sublicensable licence to use delivered Digital Content for your personal, non-commercial use only.",
                "10.3 Unless we expressly agree otherwise in writing, you must not:",
                "(a) reproduce, publish, distribute, sell, sublicense, rent, or commercially exploit any Digital Content;",
                "(b) remove proprietary notices;",
                "(c) share purchased content as part of a commercial offering, course, coaching service, or resale product; or",
                "(d) create derivative commercial products based on Service outputs.",
                "10.4 You retain ownership of materials you lawfully submit to the Service, but you grant us a non-exclusive, worldwide, royalty-free licence to host, store, reproduce, adapt, and process such materials as reasonably necessary to operate, secure, maintain, and improve the Service, subject to applicable law and our Privacy Policy.",
            ],
        },
        {
            type: "text",
            title: "11. Service Availability and Technical Issues",
            bullets: [
                "11.1 We do not guarantee that the Service will be uninterrupted, error-free, or available at all times.",
                "11.2 We may perform maintenance, updates, security actions, moderation actions, or technical interventions that temporarily affect access to the Service.",
                "11.3 We are not responsible for interruptions, delays, or failures caused by internet outages, device issues, browser incompatibility, user-side software problems, force majeure events, or failures of third-party providers outside our reasonable control.",
                "11.4 If delivery fails due to a technical issue attributable to us, we may, at our discretion, re-deliver the relevant Digital Content, correct the issue, restore the relevant Tokens, or otherwise provide an appropriate remedy.",
            ],
        },
        {
            type: "text",
            title: "12. Warranties and Disclaimers",
            bullets: [
                "12.1 We warrant that we are entitled to operate the Service and grant the rights expressly stated in these Terms.",
                "12.2 Except as expressly provided in these Terms and to the fullest extent permitted by law, the Service and all Digital Content are provided on an “as is” and “as available” basis.",
                "12.3 We do not guarantee:",
                "(a) that any course, plan, or output will meet your individual expectations or culinary preferences;",
                "(b) that any output will be suitable for every user or kitchen environment;",
                "(c) that any AI-generated output will be free from all error or omission;",
                "(d) that any chef-created output will be free from all subjective disagreement; or",
                "(e) uninterrupted access to the Service.",
            ],
        },
        {
            type: "text",
            title: "13. Limitation of Liability",
            bullets: [
                "13.1 Nothing in these Terms excludes or limits liability where such exclusion or limitation is prohibited by law, including liability for death or personal injury caused by negligence, fraud, fraudulent misrepresentation, or any other liability that cannot lawfully be excluded.",
                "13.2 Subject to clause 13.1, our total aggregate liability arising out of or in connection with the Service, any Order, or these Terms shall not exceed the total amount actually paid by you to us through the Service during the 12 months preceding the event giving rise to the claim.",
                "13.3 Subject to clause 13.1, we shall not be liable for any indirect, incidental, special, consequential, or punitive loss, or for any loss of profit, revenue, business, goodwill, opportunity, or data.",
                "13.4 If you are a consumer, this clause does not affect rights that cannot be waived or limited under mandatory consumer law.",
            ],
        },
        {
            type: "text",
            title: "14. Indemnity",
            bullets: [
                "14.1 To the extent permitted by law, you agree to indemnify and hold harmless the Company and its directors, officers, employees, contractors, and agents from and against claims, losses, liabilities, damages, and reasonable costs arising out of or connected with:",
                "(a) your breach of these Terms;",
                "(b) your unlawful or improper use of the Service;",
                "(c) your infringement of third-party rights; or",
                "(d) false, unlawful, or misleading information submitted by you.",
            ],
        },
        {
            type: "text",
            title: "15. Privacy and Data Protection",
            bullets: [
                "15.1 We process personal data in accordance with our Privacy Policy and applicable data protection law, including the UK GDPR and the Data Protection Act 2018.",
                "15.2 By using the Service, you acknowledge that your personal data may be processed for account administration, payment handling, service delivery, customer support, security, fraud prevention, legal compliance, and related legitimate business purposes as described in our Privacy Policy.",
            ],
        },
        {
            type: "text",
            title: "16. Third-Party Services and Links",
            bullets: [
                "16.1 The Service may use or contain links to third-party providers and services, including payment processors, hosting providers, analytics tools, communication tools, AI providers, and external websites.",
                "16.2 We do not control third-party services or websites and are not responsible for their content, availability, actions, or privacy practices.",
                "16.3 Your use of third-party services may be subject to their own separate terms and policies.",
            ],
        },
        {
            type: "text",
            title: "17. Suspension and Termination",
            bullets: [
                "17.1 We may suspend, restrict, or terminate your access to the Service or your Account with immediate effect where reasonably necessary, including where:",
                "(a) you breach these Terms;",
                "(b) we suspect fraud, abuse, or unlawful activity;",
                "(c) your conduct creates security, legal, operational, or reputational risk;",
                "(d) payment has been reversed or is under dispute; or",
                "(e) we are required to do so by law or by a competent authority.",
                "17.2 We may suspend delivery of Digital Content while investigating suspected abuse, chargeback activity, unauthorised payments, or materially inaccurate user information.",
                "17.3 Suspension or termination does not affect rights, remedies, or obligations that accrued before the date of suspension or termination.",
                "17.4 Clauses that by their nature should survive termination will continue in force, including clauses concerning payment, refunds, liability, intellectual property, dispute resolution, and data protection.",
            ],
        },
        {
            type: "text",
            title: "18. Changes to the Terms",
            bullets: [
                "18.1 We may update these Terms from time to time for legal, regulatory, technical, commercial, or operational reasons.",
                "18.2 The most current version will be published on the Service with the revised effective date.",
                "18.3 Where changes are material, we may provide additional notice by email, through your Account, or on the website.",
                "18.4 Your continued use of the Service after the updated Terms take effect constitutes acceptance of the revised Terms.",
            ],
        },
        {
            type: "text",
            title: "19. Notices",
            bullets: [
                `19.1 Notices to us must be sent to ${COMPANY_EMAIL}, unless we specify another contact method.`,
                "19.2 We may send notices to you using the email address associated with your Account, by in-service notification, or by posting notice on the Service.",
            ],
        },
        {
            type: "text",
            title: "20. Governing Law and Jurisdiction",
            bullets: [
                "20.1 These Terms and any non-contractual obligations arising out of or in connection with them shall be governed by the laws of England and Wales.",
                "20.2 If you are acting in the course of business, the courts of England and Wales shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms.",
                "20.3 If you are a consumer, nothing in these Terms deprives you of any mandatory protections granted by the laws of your country of habitual residence where such protections apply and cannot be excluded by contract.",
                "20.4 Consumer disputes may also be resolved through applicable out-of-court consumer dispute mechanisms where required or permitted by law.",
            ],
        },
        {
            type: "text",
            title: "21. Miscellaneous",
            bullets: [
                "21.1 If any provision of these Terms is found invalid, illegal, or unenforceable, the remaining provisions shall remain in full force and effect.",
                "21.2 Our delay or failure to enforce any provision of these Terms shall not constitute a waiver of that provision or any other right.",
                "21.3 You may not assign, transfer, or otherwise dispose of your rights or obligations under these Terms without our prior written consent.",
                "21.4 We may assign or transfer our rights and obligations in connection with a merger, acquisition, restructuring, business transfer, or sale of assets.",
                "21.5 These Terms, together with any policies expressly referenced in them, constitute the entire agreement between you and us regarding the Service and supersede prior discussions or understandings relating to the same subject matter.",
            ],
        },
        {
            type: "text",
            title: "22. Contact Details",
            bullets: [
                COMPANY_LEGAL_NAME,
                `Company Number: ${COMPANY_NUMBER}`,
                `Address: ${COMPANY_ADDRESS}`,
                `Email: ${COMPANY_EMAIL}`,
                `Phone: ${COMPANY_PHONE}`,
            ],
        },
    ],
};

//test

export default termsSchema;